### ISSUE TITLE
"command not found" when tab-completing aura -D

### ISSUE THREAD

**Issue by LogExE** [fosskers/aura#808]
when i try to use tab-completion on aura -D, it gives me this message:
```
_aura_comp:20: command not found: _aura_action_database
```
when it should give list of options to -D flag instead

**Comment by fosskers** [comment]
What shell do you use?

**Comment by LogExE** [comment]
zsh

**Comment by fosskers** [comment]
Thank you, I will confirm this when I'm able.

**Comment by alex3236** [comment]
I can confirm this. It works fine on bash, but not zsh.
```shell
$ aura -D_aura_comp:20: command not found: _aura_action_database
_aura_comp:20: command not found: _aura_action_database
_aura_comp:20: command not found: _aura_action_database
aura   
```

**Comment by fosskers** [comment]
Thanks for the confirmation. The ZSH completions haven't been updated in some time, but they look fairly straight-forward. Either a manual tweak or a recopy of `pacman`'s should fix it.

**Comment by fosskers** [comment]
zsh completions have been reworked.

**Comment by eaxly** [comment]
I am still having this issue with aura version `4.0.8`, also on zsh.

**Comment by fosskers** [comment]
I will double-check.
